name: Release

on:
  push:
    tags:
      - "v*.*.*" # Runs on version tag pushes (e.g., v1.2.3)

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release

      - name: Rename Binary for OS
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            mv target/release/shadow_jar target/release/shadow_jar-linux
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv target/release/shadow_jar target/release/shadow_jar-macos
          fi
        shell: bash
        if: runner.os != 'Windows'

      - name: Rename Windows Binary
        run: rename target\release\ShadowJar.exe ShadowJar-windows.exe
        shell: cmd
        if: runner.os == 'Windows'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            target/release/shadow_jar-linux
            target/release/shadow_jar-macos
            target/release/ShadowJar-windows.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Generate Changelog
        id: changelog
        run: |
          # Check if there's a previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            echo "🔹 No previous tag found. Generating full commit history."
            git log --pretty=format:"- %s" > changelog.md
          else
            echo "🔹 Found previous tag: $PREV_TAG. Generating changes since then."
            git log $PREV_TAG..HEAD --pretty=format:"- %s" > changelog.md
          fi

          echo "" >> changelog.md
          echo "🚀 **Release:** ${{ github.ref_name }}" >> changelog.md

      - name: List Downloaded Files
        run: ls -R ./artifacts

      - name: Upload All Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }} # Make sure to add your PAT in repo secrets
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: changelog.md
          draft: false
          prerelease: false
          files: |
            ./artifacts/binaries-windows-latest/ShadowJar-windows.exe
            ./artifacts/binaries-ubuntu-latest/shadow_jar-linux
            ./artifacts/binaries-macos-latest/shadow_jar-macos
