name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo fmt --check

      - name: Lint Code
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --verbose

      - name: Build Project
        run: cargo build --release
